### ISSUE TITLE
log spam

### ISSUE THREAD

**Issue by BakaTekku** [Inoyuuuuu/FastClimbingV2#2]
Sprinting or simply holding shift will spam the log
`[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8
[Info   :FastClimbingV2] 1.8`

**Comment by Inoyuuuuu** [comment]
oops, forgot to reset some debug stuff. Will fix that ~shortly~ tomorrow (since it's nothing game breaking, i hope that's okay with you).

**Comment by BakaTekku** [comment]
Yeah np thanks for looking into it.

**Comment by Inoyuuuuu** [comment]
Update is out and the log spam should be fixed. Sorry for the inconvenience and thank you for reporting the issue! c:
